// Added feature 1
pipeline {
    agent any 
    
   

    stages {
        stage('Clean') {
            steps {
                // Running a shell command to clean the project
               sh 'mvn -f amazon/pom.xml clean install'
            }
        }
        stage('Build') {
            steps {
                // Running the actual build
                sh 'mvn -f amazon/pom.xml install -DskipTests'
            }
        }
   
}
    post {
        success {
            slackSend(channel: '#devops-builds', 
                      color: 'good', 
                      message: "✅ Build Successful: ${env.JOB_NAME} [${env.BUILD_NUMBER}] (${env.BUILD_URL})")
        }
        failure {
            slackSend(channel: '#devops-builds', 
                      color: 'danger', 
                      message: "❌ Build Failed: ${env.JOB_NAME} [${env.BUILD_NUMBER}] (${env.BUILD_URL})")
        }
    }
}
